OUTFILE=final_methods_mistral7B_fp32.csv
PYFILE=profile_mistral7B.py
GPUID=3
CUDA_VISIBLE_DEVICES=$GPUID python $PYFILE --ths 0.375   --filename $OUTFILE --cuths 0.375
CUDA_VISIBLE_DEVICES=$GPUID python $PYFILE --ths 0.75    --filename $OUTFILE --cuths 0.75
CUDA_VISIBLE_DEVICES=$GPUID python $PYFILE --ths 1.125   --filename $OUTFILE --cuths 1.125
CUDA_VISIBLE_DEVICES=$GPUID python $PYFILE --ths 1.5     --filename $OUTFILE --cuths 1.5
CUDA_VISIBLE_DEVICES=$GPUID python $PYFILE --ths 1.875   --filename $OUTFILE --cuths 1.875
CUDA_VISIBLE_DEVICES=$GPUID python $PYFILE --ths 2.25    --filename $OUTFILE --cuths 2.25
CUDA_VISIBLE_DEVICES=$GPUID python $PYFILE --ths 2.625   --filename $OUTFILE --cuths 2.625
CUDA_VISIBLE_DEVICES=$GPUID python $PYFILE --ths 3       --filename $OUTFILE --cuths 3
CUDA_VISIBLE_DEVICES=$GPUID python $PYFILE --ths 3.375   --filename $OUTFILE --cuths 3.375
CUDA_VISIBLE_DEVICES=$GPUID python $PYFILE --ths 3.75    --filename $OUTFILE --cuths 3.75
CUDA_VISIBLE_DEVICES=$GPUID python $PYFILE --ths 4.125   --filename $OUTFILE --cuths 4.125
CUDA_VISIBLE_DEVICES=$GPUID python $PYFILE --ths 4.5     --filename $OUTFILE --cuths 4.5
CUDA_VISIBLE_DEVICES=$GPUID python $PYFILE --ths 4.875   --filename $OUTFILE --cuths 4.875
